# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DuxJwBwbDLES_1rdc4MdMmXn_XGnv0YH
"""

a = input ("nama :")
b = input ("makanan kesukaan :")
print("hai",a,"yang terhormat",b,"memang paling enak didunia")
print("kesulitan jawab matematika?")
c = int(input("bilangan1 :"))
d = int(input("bilangan2 :"))
print(c*d)

print("selamat datang di KABUQIE mau cari apa?")
print("silahkan pilih operasi")
print("1.luas")
print("2.volume")
a = input("pilihan anda :")
c = int(input("bilangan r :"))
d = int(input("tinggi kerucut :"))
if a == 1 :
  b = 22/7*c*c
else: b = 1/3*22/7*c*c*d
print(b)



a = int(input("nilai r :"))
b = int(input("nilai tinggi :"))
print(1/3*22/7*a*a*b)